/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    motherboards: Motherboard;
    processors: Processor;
    gpus: Gpus;
    ram: Ram;
    psus: Psus;
    cases: Case;
    coolers: Cooler;
    storage: Storage;
    builds: Build;
    orders: Order;
    brands: Brand;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    motherboards: MotherboardsSelect<false> | MotherboardsSelect<true>;
    processors: ProcessorsSelect<false> | ProcessorsSelect<true>;
    gpus: GpusSelect<false> | GpusSelect<true>;
    ram: RamSelect<false> | RamSelect<true>;
    psus: PsusSelect<false> | PsusSelect<true>;
    cases: CasesSelect<false> | CasesSelect<true>;
    coolers: CoolersSelect<false> | CoolersSelect<true>;
    storage: StorageSelect<false> | StorageSelect<true>;
    builds: BuildsSelect<false> | BuildsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ru' | 'ky') | ('en' | 'ru' | 'ky')[];
  globals: {
    about: About;
    contacts: Contact;
    'featured-product-list': FeaturedProductList;
    feedback: Feedback;
    instruction: Instruction;
    'instruction-configurator': InstructionConfigurator;
  };
  globalsSelect: {
    about: AboutSelect<false> | AboutSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    'featured-product-list': FeaturedProductListSelect<false> | FeaturedProductListSelect<true>;
    feedback: FeedbackSelect<false> | FeedbackSelect<true>;
    instruction: InstructionSelect<false> | InstructionSelect<true>;
    'instruction-configurator': InstructionConfiguratorSelect<false> | InstructionConfiguratorSelect<true>;
  };
  locale: 'en' | 'ru' | 'ky';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role?: ('admin' | 'user') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "motherboards".
 */
export interface Motherboard {
  id: number;
  name: string;
  brand: number | Brand;
  price: number;
  image?: (number | null) | Media;
  description?: string | null;
  stock_quantity: number;
  socket: string;
  form_factor: 'ATX' | 'Micro-ATX' | 'Mini-ITX';
  supports_ddr4?: boolean | null;
  supports_ddr5?: boolean | null;
  ram_slots: number;
  m2_slots: number;
  sata_ports: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  slug: string;
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "processors".
 */
export interface Processor {
  id: number;
  name: string;
  brand: number | Brand;
  price: number;
  image?: (number | null) | Media;
  description?: string | null;
  stock_quantity: number;
  socket: 'LGA1700' | 'LGA1200' | 'AM4' | 'AM5' | 'TR4';
  tdp: number;
  supports_ddr4?: boolean | null;
  supports_ddr5?: boolean | null;
  has_graphics?: boolean | null;
  fps_multiplier: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Видеокарты
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gpus".
 */
export interface Gpus {
  id: number;
  name: string;
  brand: number | Brand;
  price: number;
  image?: (number | null) | Media;
  description?: string | null;
  stock_quantity: number;
  length_mm: number;
  recommended_psu_w: number;
  connector_8pin: number;
  connector_16pin?: boolean | null;
  fps_presets: {
    esports: number;
    aaa: number;
    casual: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Оперативная память
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ram".
 */
export interface Ram {
  id: number;
  name: string;
  brand: number | Brand;
  price: number;
  image?: (number | null) | Media;
  description?: string | null;
  stock_quantity: number;
  type: 'DDR4' | 'DDR5';
  modules_count: number;
  total_capacity_gb: number;
  speed_mhz: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "psus".
 */
export interface Psus {
  id: number;
  name: string;
  brand: number | Brand;
  price: number;
  image?: (number | null) | Media;
  description?: string | null;
  stock_quantity: number;
  wattage: number;
  form_factor: 'ATX' | 'SFX' | 'SFX-L';
  pcie_connectors: number;
  has_16pin_connector?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases".
 */
export interface Case {
  id: number;
  name: string;
  brand: number | Brand;
  price: number;
  image?: (number | null) | Media;
  description?: string | null;
  stock_quantity: number;
  supports_atx?: boolean | null;
  supports_matx?: boolean | null;
  supports_itx?: boolean | null;
  max_gpu_length_mm: number;
  max_cooler_height_mm: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coolers".
 */
export interface Cooler {
  id: number;
  name: string;
  brand: number | Brand;
  price: number;
  image?: (number | null) | Media;
  description?: string | null;
  stock_quantity: number;
  supports_lga1700?: boolean | null;
  supports_am4?: boolean | null;
  supports_am5?: boolean | null;
  /**
   * Должно быть выше TDP процессора
   */
  max_tdp: number;
  /**
   * Проверяется на совместимость с шириной корпуса
   */
  height_mm: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storage".
 */
export interface Storage {
  id: number;
  name: string;
  brand: string;
  price: number;
  image?: (number | null) | Media;
  description?: string | null;
  stock_quantity: number;
  type: 'NVMe' | 'SATA SSD' | 'HDD';
  interface: 'M.2' | 'SATA';
  /**
   * Укажите объем в гигабайтах (например, 1024 для 1ТБ)
   */
  capacity_gb: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "builds".
 */
export interface Build {
  id: number;
  user: number | User;
  name: string;
  is_complete?: boolean | null;
  cpu?: (number | null) | Processor;
  mobo?: (number | null) | Motherboard;
  gpu?: (number | null) | Gpus;
  ram?: (number | null) | Ram;
  psu?: (number | null) | Psus;
  case?: (number | null) | Case;
  cooler?: (number | null) | Cooler;
  storage?: (number | null) | Storage;
  tags?: ('gaming' | 'budget' | 'workstation')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  user: number | User;
  build: number | Build;
  status: 'pending' | 'paid' | 'shipped' | 'delivered' | 'cancelled';
  total_price: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'motherboards';
        value: number | Motherboard;
      } | null)
    | ({
        relationTo: 'processors';
        value: number | Processor;
      } | null)
    | ({
        relationTo: 'gpus';
        value: number | Gpus;
      } | null)
    | ({
        relationTo: 'ram';
        value: number | Ram;
      } | null)
    | ({
        relationTo: 'psus';
        value: number | Psus;
      } | null)
    | ({
        relationTo: 'cases';
        value: number | Case;
      } | null)
    | ({
        relationTo: 'coolers';
        value: number | Cooler;
      } | null)
    | ({
        relationTo: 'storage';
        value: number | Storage;
      } | null)
    | ({
        relationTo: 'builds';
        value: number | Build;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "motherboards_select".
 */
export interface MotherboardsSelect<T extends boolean = true> {
  name?: T;
  brand?: T;
  price?: T;
  image?: T;
  description?: T;
  stock_quantity?: T;
  socket?: T;
  form_factor?: T;
  supports_ddr4?: T;
  supports_ddr5?: T;
  ram_slots?: T;
  m2_slots?: T;
  sata_ports?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "processors_select".
 */
export interface ProcessorsSelect<T extends boolean = true> {
  name?: T;
  brand?: T;
  price?: T;
  image?: T;
  description?: T;
  stock_quantity?: T;
  socket?: T;
  tdp?: T;
  supports_ddr4?: T;
  supports_ddr5?: T;
  has_graphics?: T;
  fps_multiplier?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gpus_select".
 */
export interface GpusSelect<T extends boolean = true> {
  name?: T;
  brand?: T;
  price?: T;
  image?: T;
  description?: T;
  stock_quantity?: T;
  length_mm?: T;
  recommended_psu_w?: T;
  connector_8pin?: T;
  connector_16pin?: T;
  fps_presets?:
    | T
    | {
        esports?: T;
        aaa?: T;
        casual?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ram_select".
 */
export interface RamSelect<T extends boolean = true> {
  name?: T;
  brand?: T;
  price?: T;
  image?: T;
  description?: T;
  stock_quantity?: T;
  type?: T;
  modules_count?: T;
  total_capacity_gb?: T;
  speed_mhz?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "psus_select".
 */
export interface PsusSelect<T extends boolean = true> {
  name?: T;
  brand?: T;
  price?: T;
  image?: T;
  description?: T;
  stock_quantity?: T;
  wattage?: T;
  form_factor?: T;
  pcie_connectors?: T;
  has_16pin_connector?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases_select".
 */
export interface CasesSelect<T extends boolean = true> {
  name?: T;
  brand?: T;
  price?: T;
  image?: T;
  description?: T;
  stock_quantity?: T;
  supports_atx?: T;
  supports_matx?: T;
  supports_itx?: T;
  max_gpu_length_mm?: T;
  max_cooler_height_mm?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coolers_select".
 */
export interface CoolersSelect<T extends boolean = true> {
  name?: T;
  brand?: T;
  price?: T;
  image?: T;
  description?: T;
  stock_quantity?: T;
  supports_lga1700?: T;
  supports_am4?: T;
  supports_am5?: T;
  max_tdp?: T;
  height_mm?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storage_select".
 */
export interface StorageSelect<T extends boolean = true> {
  name?: T;
  brand?: T;
  price?: T;
  image?: T;
  description?: T;
  stock_quantity?: T;
  type?: T;
  interface?: T;
  capacity_gb?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "builds_select".
 */
export interface BuildsSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  is_complete?: T;
  cpu?: T;
  mobo?: T;
  gpu?: T;
  ram?: T;
  psu?: T;
  case?: T;
  cooler?: T;
  storage?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  user?: T;
  build?: T;
  status?: T;
  total_price?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  title: string;
  description?: string | null;
  mission?: string | null;
  founded_year?: number | null;
  team_size?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  working_hours?: string | null;
  telegram?: string | null;
  whatsapp?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-product-list".
 */
export interface FeaturedProductList {
  id: number;
  title?: string | null;
  items?:
    | {
        build: number | Build;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback".
 */
export interface Feedback {
  id: number;
  is_enabled?: boolean | null;
  recipient_email?: string | null;
  success_message?: string | null;
  fields?:
    | {
        name: string;
        type: 'name' | 'email' | 'message';
        required?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instruction".
 */
export interface Instruction {
  id: number;
  title: string;
  intro?: string | null;
  /**
   * Рекомендуемый размер: 1920×400 px
   */
  banner?: (number | null) | Media;
  steps?:
    | {
        title: string;
        description: string;
        tip?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instruction-configurator".
 */
export interface InstructionConfigurator {
  id: number;
  title: string;
  intro?: string | null;
  banner?: (number | null) | Media;
  steps?:
    | {
        title: string;
        description: string;
        tip?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  mission?: T;
  founded_year?: T;
  team_size?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  phone?: T;
  email?: T;
  address?: T;
  working_hours?: T;
  telegram?: T;
  whatsapp?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-product-list_select".
 */
export interface FeaturedProductListSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        build?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback_select".
 */
export interface FeedbackSelect<T extends boolean = true> {
  is_enabled?: T;
  recipient_email?: T;
  success_message?: T;
  fields?:
    | T
    | {
        name?: T;
        type?: T;
        required?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instruction_select".
 */
export interface InstructionSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  banner?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        tip?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instruction-configurator_select".
 */
export interface InstructionConfiguratorSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  banner?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        tip?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}